spring.application.name=pmt
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/pmt_db
spring.datasource.username=postgres
spring.datasource.password=pmtpassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=2694b7f7458b48
spring.mail.password=d8c4665d25e325
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true

















// Looking to send emails in production? Check out our Email API/SMTP product!
var transport = nodemailer.createTransport({
host: "sandbox.smtp.mailtrap.io",
port: 2525,
auth: {
user: "2694b7f7458b48",
pass: "d8c4665d25e325"
}
});